name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install R packages
        run: Rscript -e 'install.packages(c("rmarkdown", "knitr", "ggplot2", "reticulate"))'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install the dependencies
        run: |
          python -m pip install -r requirements.txt
      - name : Run python scripts and build kuzu db
        run: |
          python3 scripts/metadata-scrape.py
          python3 scripts/load_data_kuzu.py
      - name : Build kuzu-wasm with local db
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/package/kuzu-wasm:/kuzu-wasm/packages/kuzu-wasm/dist \
            -v ${{ github.workspace }}/data:/kuzu-wasm/data/embeddings \
            dylanshang/kuzu-wasm \
            /bin/bash -c "make package"
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist